package-lock.json, package.json, src/components/CustomerInfo.jsx
Successfully tested react-datepicker library. CustomerInfo.jsx contains testing code in frontend form render area.
=> React datepicker testing

src/components/CustomerInfo.jsx
=> feat(CustomerInfo):User can create appointments

package-lock.json, src/components/CustomerInfo.jsx
=> refactor(CustomerInfo): pass in more customer information to post

package-lock.json, package.json, public/index.html, public/styles/style.css, src/components/CustomerInfo.jsx, src/components/containers/AllBarbers.jsx, src/components/views/AllBarbers.jsx
Closes #21 
Created styles folder in public director and installed/tested modal library on frontend.
=> Create styles directory #21

src/app/App.js, src/components/CustomerInfo.jsx, src/components/containers/AllBarbers.jsx, src/components/views/AllBarbers.jsx
Closes #24 
Clicking a barber now sets the current barber on state, then opens the appointment form in a modal, in that order.
=> Cleanup barber grid #24

package-lock.json, public/styles/style.css, src/app/App.css, src/app/App.js, src/components/views/AllBarbers.jsx, src/index.css
=> Standardize barber grid #26

src/components/containers/AllBarbersContainer.jsx, src/components/containers/AppointmentFormContainer.jsx, src/components/views/AppointmentFormView.jsx, src/reducers/index.js, src/store/utilities/bookedAppointments.js, src/store/utilities/currentBarber.js, src/thunks/index.js
=> Black out booked time slots #40

src/components/containers/AppointmentFormContainer.jsx, src/components/views/AppointmentFormView.jsx
=> feat(AppointmentForm): Exclude fully booked days for a barber

package-lock.json, public/styles/style.css, src/components/views/modules/AppointmentFormView.jsx
=> style(style.css): styled appointment form

src/components/containers/HeaderContainer.jsx, src/components/containers/modules/LoginFormContainer.jsx, src/components/containers/modules/index.js, src/components/views/modules/LoginFormView.jsx
=> feat(LoginForm): establish log in form

src/components/containers/modules/LoginFormContainer.jsx, src/reducers/index.js, src/store/utilities/currentUser.js, src/thunks/index.js
=> feat(currentUser): Add User Reducer

src/app/App.js, src/components/containers/modules/BarberAppointmentsContainer.jsx, src/components/containers/modules/index.js, src/components/views/modules/BarberAppointmentsView.jsx, src/components/views/modules/index.js
=> feat(BarberAppointments): Display appointments for logged in barber

src/components/containers/HeaderContainer.jsx, src/components/containers/LoginFormContainer.jsx, src/components/containers/LogoutContainer.jsx, src/components/containers/index.js, src/components/containers/modules/index.js, src/components/views/LoginFormView.jsx, src/components/views/LogoutView.jsx, src/components/views/index.js, src/store/utilities/currentUser.js
=> feat(Logout): Create logout button container and view

src/app/App.js, src/components/containers/FooterContainer.jsx, src/components/containers/HeaderContainer.jsx, src/components/containers/LoginFormContainer.jsx, src/components/containers/LogoutContainer.jsx, src/components/containers/MainContainer.jsx, src/index.js
=> Wire up browser router and test history #70

src/components/containers/HeaderContainer.jsx
=> feat(Login/Logout): Render the appropriate button

src/components/containers/HeaderContainer.jsx, src/components/containers/modules/ServicesContainer.jsx, src/components/containers/modules/index.js, src/components/views/modules/ServicesView.jsx, src/components/views/modules/index.js
=> Create services container #76

src/components/containers/modules/ServicesContainer.jsx, src/components/views/MainView.jsx, src/components/views/modules/ServicesView.jsx
=> Select and unselect services #81

src/store/utilities/allBarbers.js
=> fix(allBarbers): Set default barber when page loads

src/components/views/RoutesView.jsx
=> Default to dashboard route #91

src/components/containers/modules/Main/Dashboard/DashboardContainer.jsx, src/components/containers/modules/Main/Dashboard/DashboardMenuContainer.jsx, src/components/views/modules/Main/Dashboard/DashboardMenuView.jsx, src/reducers/index.js, src/store/utilities/coworkerAppointments.js, src/store/utilities/currentBarber.js, src/thunks/index.js
=> fix(Dashboard): Fix appointments handlers for customers and barbers

src/components/containers/modules/Main/Landing/ReviewFormContainer.jsx, src/components/containers/modules/Main/index.js, src/components/views/RoutesView.jsx, src/components/views/modules/Main/Landing/ReviewFormView.jsx, src/components/views/modules/Main/index.js
=> Create review form container #102

public/styles/style.css, src/app/App.js, src/components/containers/HeaderContainer.jsx, src/components/views/FooterView.jsx, src/components/views/HeaderView.jsx, src/components/views/modules/Main/Landing/AppointmentForm/AppointmentFormView.jsx, src/components/views/modules/Main/Landing/AppointmentForm/CustomerInfoView.jsx, src/components/views/modules/Main/Landing/LandingView.jsx, src/components/widgets/Switcher.jsx
=> Cleanup styles #110
